---
title: "Vahey et al. 2010 Analysis"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
---

This project attempts to recreate the analysis presented in the paper:  
  
Expression of Genes Associated with Immunoproteaseome Processing of Major Histocompabtibility Complex Peptides is Indicative of Protection with Adjuvanated RTS,S Malaria Vaccine, Vahey et al. The Journal of Infectious Disease 2010:201:580-9

##Experimental Design  
###[Design](experimental_design.html)  
####[Quality Control](QC.html)  

##Analysis

###GSEA
####[T0 vs T1 to T5: time effect](GSEA_T0.html)  
####[T1 vs T2 to T5: time effect](GSEA_T1.html)  
####[T0 vs T1 to T5: time*disease interaction effect](GSEA_T0_Interaction.html)  
####[T1 vs T2 to T5: time*disease interaction effect](GSEA_T1_Interaction.html)  
####[Disease effects](GSEA_Disease.html)

###DEG
####[T0 vs T1 to T5: time effect](DEG_T0.html)  
####[T1 vs T2 to T5: time effect](DEG_T1.html)  
####[T0 vs T1 to T5: time*disease interaction effect](DEG_T0_Interaction.html)  
####[T1 vs T2 to T5: time*disease interaction effect](DEG_T1_Interaction.html)
####[Disease effects](DEG_Disease.html)

###Exploratory  
####[monocyte/lymphocyte ratio disease prediction](ciber_MLratio.html)

##Paper Reproduction 
####[Fig1: DEG: T1 vs T2 and T3](analysis_DEG.html)  
####[Fig2: PCA: Controls vs Protected vs NonProtected](analysis_PCA.html)  
####[Fig3: PAM analysis](pamr.html)
####[Fig4: GSEA: T4 vaccine vs no-vaccine](analysis_GSEA.html)  


##Appendix
####[Processing](processVahey.html)

