---
title: Process Vahey et al, 2018 Microarry PBMC Data
author: Carl Murie
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: html_document
---

```{r load-packages, echo=FALSE, warning=FALSE, message=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message=FALSE)
library(GEOquery)
library(Biobase)
library(tidyverse)
library(magrittr)
library(here)
```


##Obtaining normalized data and meta-data from GEO

```{r getSome}
setwd(here("data"))

geoID <- "GSE18323"

## get the data. There are two elements
geoDat <- getGEO(geoID, destdir=".")

gpl570 <- geoDat[[1]]        ##V5 with HGU133 Plus chip (39 samples)
gpl571 <- geoDat[[2]]        ##V0 to V4 with HGU133A chip (215 samples)

# check that they are ordered properly
if(sum(colnames(exprs(geoDat[[1]])) != rownames(pData(geoDat[[1]]))) >0) {
  stop("Mismatched data in gpl571")
} 

if(sum(colnames(exprs(geoDat[[2]])) != rownames(pData(geoDat[[2]]))) >0) {
  stop("Mismatched data in gpl570")
} 
```

##Reformat data

```{r process}
## extract only the useful meta data columns and create necessary factors
pData(gpl570) %>%
  select(title, 
         geo_accession,
         'group:ch1')  %>%
  rename(description=title,
         geo_id=geo_accession,
         parasitemia="group:ch1") %>%
  mutate(description=as.character(description),
         pid=word(description, start=2),
         disease=plyr::mapvalues(parasitemia, from="Delay", to="NonProtected"),
         visit="T5",
         chip="HGU133Plus") %>%
  set_rownames(pData(gpl570)$geo_accession) ->
  pData(gpl570)

##sum(colnames(exprs(gpl570)) != rownames(pData(gpl570))) 

# extract only the useful meta data columns
pData(gpl571)[,c("title", "geo_accession", "group:ch1")] %>%
  rename(description=title,
         geo_id=geo_accession,
         parasitemia="group:ch1") %>%
  mutate(description=as.character(description),
         pid=word(description, start=2),
         pid=str_remove(pid, ","),
         disease=plyr::mapvalues(parasitemia, from="Delay", to="NonProtected"),
         visit=word(description, start=6),
         chip="HGU133A") %>%
  set_rownames(pData(gpl571)$geo_accession) ->
  pData(gpl571)

##sum(colnames(exprs(gpl571)) != rownames(pData(gpl571))) 
```

##Subset genes on intersection of both chips  
  
The HGU133A 2.0 gene chip has 22277 transcripts while the HGU133 Plus 2.0 has 54675 transcripts. Use only the 22277 transcripts found in the HGU133A 2.0 gene chip  
  

```{r test_transcript, echo=FALSE, eval=FALSE}

pData(gpl571) %>% 
  filter(!is.na(visit)) %>%           ## remove controls
  filter(disease != "Unknown") %$%    ## remove Unknown subjects - no samples for T0 or T5
    geo_id ->
  sample_index

deg_eset <- gpl571[,sample_index]

design1 <- model.matrix(formula("~visit"), data=pData(deg_eset))
v1 <- voom(exprs(deg_eset), design=design1)
dupCor <- duplicateCorrelation(v1, design=design1,
                               block=deg_eset$pid)$consensus.correlation
fit1 <- lmFit(v1, design1, block=deg_eset$pid, correlation=dupCor)
eb_fit1 <- eBayes(fit1)

fit1_t <- topTable(eb_fit1, number=Inf, coef="visitT1", sort.by="P")
ggplot(fit1_t, aes(x=P.Value)) + geom_histogram()

fit1_t <- topTable(eb_fit1, number=Inf, coef="visitT2", sort.by="P")
ggplot(fit1_t, aes(x=P.Value)) + geom_histogram()

fit1_t <- topTable(eb_fit1, number=Inf, coef="visitT3", sort.by="P")
ggplot(fit1_t, aes(x=P.Value)) + geom_histogram()

fit1_t <- topTable(eb_fit1, number=Inf, coef="visitT4", sort.by="P")
ggplot(fit1_t, aes(x=P.Value)) + geom_histogram()

```



```{r filter}
gpl570 <- gpl570[rownames(gpl570) %in% rownames(gpl571),]
```



##Map transcript ids to gene symbols

```{r map}

## TODO look at purr for another way of doing this
reads_570 <- apply(exprs(gpl570), 2, 
                function(x) tapply(x, fData(gpl570)$"Gene Symbol", sum))[-1,]
reads_571 <- apply(exprs(gpl571), 2, 
                function(x) tapply(x, fData(gpl571)$"Gene Symbol", sum))[-1,]

if(sum(rownames(reads_570) != rownames(reads_571)) >0) {
  stop("mapping to gene symbols failed")
} 
```

##Combine the 2 ExpressionSets

```{r subset}

## combine two ExpressionSets
##annotation(gpl570) <- annotation(gpl571)
##gpl <- BiocGenerics::combine(gpl571, gpl570) # doesn't work

## combine the hard way
gpl <- ExpressionSet(cbind(reads_571, reads_570))
bind_rows(pData(gpl571), pData(gpl570)) %>%
  set_rownames(c(pData(gpl571)$geo_id, pData(gpl570)$geo_id)) -> 
  pData(gpl)

## check that they are ordered properly
if(sum(colnames(exprs(gpl)) != rownames(pData(gpl))) >0) {
  stop("Mismatched data in gpl")
} 
```

##Save filtered and combined ExpressionSet for further analysis  

```{r save}
saveRDS(gpl, here("data", "gpl_eset.Rds"))
```
